### PR TITLE
Update and rename burger-Meal.md to Response-Codes.md

### PR DESCRIPTION
**Pull request by miriam1986**
Populated the file and changed the name to Response-Codes.

### CODE REVIEW

**Comment by Laura-Novich-OBW** [comment]
Please add 404 to the table

**Review by miriam1986 — COMMENTED** [review]
404 response added ad requested

**Review by Laura-Novich-OBW — APPROVED** [review]

**Comment by Laura-Novich-OBW** [comment]
nice job

**Comment by Laura-Novich-OBW** [comment]
Please merge

**Pull request merged**
